version: "1"

services:
  postgres:
    image: postgres
    container_name: whoami-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-whoami
    volumes:
      - data_postgres:/var/lib/postgresql/data

volumes:
  data_postgres:
